### PR TITLE
Markdown 3 support

### PR DESCRIPTION
**Pull request by linevych**

### CODE REVIEW

**Comment by Kristinita** [comment]
@cprieto, ping. It solve critical problem for Python Markdown 3 and higher. Example:

```text
ERROR: Could not process Gingerinas\Поиск-книг-для-джинджерин.md
  | AttributeError: 'Registry' object has no attribute 'keys'
ERROR: Could not process Giologica\Valerywork-Kiravel.md
  | AttributeError: 'Registry' object has no attribute 'keys'
ERROR: Could not process Sublime-Text\ValeriyaSpeller.md
  | AttributeError: 'Registry' object has no attribute 'keys'
ERROR: Could not process IT-articles\Fastest-way-to-add-new-version-of-Sublime-Text-3-package.md
  | AttributeError: 'Registry' object has no attribute 'keys'
CRITICAL: RuntimeError: generator raised StopIteration
```

Thanks.

**Comment by linevych** [comment]
`sudo ping` @cprieto ?

**Comment by fancsali** [comment]
@cprieto Can we please merge this?

**Comment by cprieto** [comment]
Sorry guys, somehow I missed this notification while on holidays and was until the last message I realized I had an open pull request in this repo.

**Comment by Kristinita** [comment]
@cprieto , can you [**publish this changes to PyPI**](https://kristinita.ru/IT-articles/How-to-publish-your-package-to-PyPI-2018)? 1.1.0 is mdx_downheader version for PyPI [**at February 3, 2019**](https://pypi.org/project/markdown-downheader/#history).

Thanks.

**Pull request merged**
